# Site settings
title: CAEPA
legal_name: Colorado Adult Education Professional Association
icon: /img/icon-color-1x.png
logo: /img/caepa-white.png
email: admin@caepa.org
description: Providing Colorado Leadership in Adult Education and Literacy since 1935
mission: The Colorado Adult Education Professional Association, CAEPA, provides leadership to the field of adult education and family literacy by offering opportunities for professional development, advocacy, and resource sharing to improve the quality of life for every Coloradan.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.caepa.org"
repository: caepa/caepa.github.io

google_analytics_id: UA-76548901-1
google_site_verification: 9aWiSPXxIMqz4XsA1BbxONHgHSSVeTczQFS0fJcgEZE

docs_path: /assets/docs/
img_path: /assets/img/

social:
# - name: dropbox url:  http://dropbox.com
# - name: google-plus url:  http://plus.google.com/caepaboard

  - name: facebook
    url:  https://www.facebook.com/caepa.co
  - name: github
    url:  http://github.com/caepa
  - name: linkedin
    url:  https://www.linkedin.com/company/colorado-adult-education-professional-association-caepa-
  - name: rss
    url:  http://news.caepa.org/feed.xml
  - name: twitter
    url:  https://twitter.com/caepa_co

# Build settings
future: true
timezone: America/Denver
markdown: kramdown
exclude:
  - _docs
include:
  - _pages

sass:
  load_paths:
    - assets/css
    - assets/css/materialize/sass
    - assets/css/mdc-typography
  style: compressed

collections:
  bylaws:
    output: true
  factsheets:
    output: true
  forms:
    output: true
  home:
    output: false # not in use
  news:
    output: false # external site
  rendezvous:
    output: true
  resources:
    output: true

defaults:
  - scope:
      type: bylaws
    values:
      layout: page-collection
  - scope:
      type: factsheets
    values:
      layout: page-collection
  - scope:
      type: forms
    values:
      layout: page-collection
  - scope:
      type: home
    values:
      layout: home
      permalink: /
  - scope:
      type: news
    values:
      layout: page-collection
  - scope:
      type: rendezvous
    values:
      layout: page-rendezvous
      permalink: /events/:title
  - scope:
      type: pages
    values:
      layout: page-collection
  - scope:
      type: posts
    values:
      layout: "post"
      author: CAEPA
      permalink: /:categories/:title
