# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Colorado Adult Education Professional Association
name: CAEPA
logo: logo.png
email: admin@caepa.org
description: >
  Providing Colorado Leadership in Adult Education and Literacy since 1935
mission: >
  The Colorado Adult Education Professional Association, CAEPA, provides leadership to the field of adult education and family literacy by offering opportunities for professional development, advocacy, and resource sharing to improve the quality of life for every Coloradan.
  
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.caepa.org/"

social_media:
# - name: dropbox url:  http://dropbox.com
# - name: google-plus url:  http://plus.google.com/caepaboard
  - name: linkedin
    url:  https://www.linkedin.com/company/colorado-adult-education-professional-association-caepa-
  - name: facebook
    url:  https://www.facebook.com/caepa.co
  - name: github
    url:  http://github.com/caepa
  - name: rss
    url:  http://blog.caepa.org/rss
  - name: twitter
    url:  https://twitter.com/intent/follow?screen_name=caepa_co

# Build settings
markdown: kramdown

collections:
  events:
    output: false
  history:
    output: true
  
include: ["_pages"]