# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: CAEPA
legal_name: Colorado Adult Education Professional Association
icon: /img/icon-1x.png
logo: /img/logo-1x.png
email: admin@caepa.org
description: Providing Colorado Leadership in Adult Education and Literacy since 1935
mission: The Colorado Adult Education Professional Association, CAEPA, provides leadership to the field of adult education and family literacy by offering opportunities for professional development, advocacy, and resource sharing to improve the quality of life for every Coloradan.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.caepa.org"

google_analytics_id: UA-76548901-1
google_site_verification: 9aWiSPXxIMqz4XsA1BbxONHgHSSVeTczQFS0fJcgEZE

social:
# - name: dropbox url:  http://dropbox.com
# - name: google-plus url:  http://plus.google.com/caepaboard
  - name: linkedin
    url:  https://www.linkedin.com/company/colorado-adult-education-professional-association-caepa-
  - name: facebook
    url:  https://www.facebook.com/caepa.co
  - name: github
    url:  http://github.com/caepa
  - name: rss
    url:  http://www.caepa.org/feed.xml
  - name: twitter
    url:  https://twitter.com/caepa_co

# Build settings
markdown: kramdown

collections:
  forms:
    output: true

include: ["_pages"]
future: true
timezone: America/Denver

defaults:
  - scope:
      path: ""
    values:
      color: grey darken-4
      color_accent: grey darken-3
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: Colorado Adult Education Professional Association
      permalink: /:categories/:title.html
      tabs: [Article, Related Articles]
  - scope:
      path: "events"
    values:
      color: red darken-4
      color_accent: red darken-3
      icon: date_range
  - scope:
      path: "fact_sheets"
    values:
      color: pink darken-4
      color_accent: pink darken-3
      icon: info
  - scope:
      path: "forms"
    values:
      color: purple darken-4
      color_accent: purple darken-3
      icon: description
  - scope:
      type: "forms"
    values:
      color: purple darken-4
      color_accent: purple darken-3
      icon: description
  - scope:
      path: "news"
    values:
      color: deep-purple darken-4
      color_accent:  deep-purple darken-3
      icon: chrome_reader_mode
  - scope:
      path: "news"
      type: "posts"
    values:
      permalink: /:categories/:year/:title.html